package com.leecp.jpa.model;
// Generated 2018-2-22 20:11:02 by Hibernate Tools 5.2.8.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * ArticleCategory generated by hbm2java
 */
@Entity
public class ArticleCategory implements java.io.Serializable {
    @Id
    @GeneratedValue
    private Integer id;
    private int articleId;
    private int categoryId;

    public ArticleCategory() {
    }

    public ArticleCategory(int articleId, int categoryId) {
        this.articleId = articleId;
        this.categoryId = categoryId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getArticleId() {
        return this.articleId;
    }

    public void setArticleId(int articleId) {
        this.articleId = articleId;
    }

    public int getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

}
