package com.leecp.jpa.model;
// Generated 2018-2-22 20:11:02 by Hibernate Tools 5.2.8.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Article generated by hbm2java
 */

@Entity
public class Article implements java.io.Serializable {
    @Id
    @GeneratedValue()
    private Integer id;
    private Integer topicId;
    private String title;
    private String author;
    private String fromurl;
    private String image;
    private String keywords;
    private String description;
    private byte type;
    private byte allowcomments;
    private byte status;
    private String content;
    private int userId;
    private int readnumber;
    private int top;
    private Integer systemId;
    private long ctime;
    private long orders;

    public Article() {
    }

    public Article(String title, byte type, byte allowcomments, byte status, int userId, int readnumber, int top,
            long ctime, long orders) {
        this.title = title;
        this.type = type;
        this.allowcomments = allowcomments;
        this.status = status;
        this.userId = userId;
        this.readnumber = readnumber;
        this.top = top;
        this.ctime = ctime;
        this.orders = orders;
    }

    public Article(Integer topicId, String title, String author, String fromurl, String image, String keywords,
            String description, byte type, byte allowcomments, byte status, String content, int userId, int readnumber,
            int top, Integer systemId, long ctime, long orders) {
        this.topicId = topicId;
        this.title = title;
        this.author = author;
        this.fromurl = fromurl;
        this.image = image;
        this.keywords = keywords;
        this.description = description;
        this.type = type;
        this.allowcomments = allowcomments;
        this.status = status;
        this.content = content;
        this.userId = userId;
        this.readnumber = readnumber;
        this.top = top;
        this.systemId = systemId;
        this.ctime = ctime;
        this.orders = orders;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getTopicId() {
        return this.topicId;
    }

    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getFromurl() {
        return this.fromurl;
    }

    public void setFromurl(String fromurl) {
        this.fromurl = fromurl;
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getKeywords() {
        return this.keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public byte getType() {
        return this.type;
    }

    public void setType(byte type) {
        this.type = type;
    }

    public byte getAllowcomments() {
        return this.allowcomments;
    }

    public void setAllowcomments(byte allowcomments) {
        this.allowcomments = allowcomments;
    }

    public byte getStatus() {
        return this.status;
    }

    public void setStatus(byte status) {
        this.status = status;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getReadnumber() {
        return this.readnumber;
    }

    public void setReadnumber(int readnumber) {
        this.readnumber = readnumber;
    }

    public int getTop() {
        return this.top;
    }

    public void setTop(int top) {
        this.top = top;
    }

    public Integer getSystemId() {
        return this.systemId;
    }

    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    public long getCtime() {
        return this.ctime;
    }

    public void setCtime(long ctime) {
        this.ctime = ctime;
    }

    public long getOrders() {
        return this.orders;
    }

    public void setOrders(long orders) {
        this.orders = orders;
    }

}
