package com.leecp.jpa.model;
// Generated 2018-2-22 20:11:02 by Hibernate Tools 5.2.8.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * ArticleTag generated by hbm2java
 */
@Entity
public class ArticleTag implements java.io.Serializable {
    @Id
    @GeneratedValue
    private Integer id;
    private int articleId;
    private int tagId;

    public ArticleTag() {
    }

    public ArticleTag(int articleId, int tagId) {
        this.articleId = articleId;
        this.tagId = tagId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getArticleId() {
        return this.articleId;
    }

    public void setArticleId(int articleId) {
        this.articleId = articleId;
    }

    public int getTagId() {
        return this.tagId;
    }

    public void setTagId(int tagId) {
        this.tagId = tagId;
    }

}
