package com.leecp.jpa.model;
// Generated 2018-2-22 20:11:02 by Hibernate Tools 5.2.8.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * CategoryTag generated by hbm2java
 */
@Entity
public class CategoryTag implements java.io.Serializable {
    @Id
    @GeneratedValue
    private Integer id;
    private int categoryId;
    private int tagId;

    public CategoryTag() {
    }

    public CategoryTag(int categoryId, int tagId) {
        this.categoryId = categoryId;
        this.tagId = tagId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    public int getTagId() {
        return this.tagId;
    }

    public void setTagId(int tagId) {
        this.tagId = tagId;
    }

}
