package com.leecp.jpa.model;
// Generated 2018-2-22 20:11:02 by Hibernate Tools 5.2.8.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Comment generated by hbm2java
 */
@Entity
public class Comment implements java.io.Serializable {
    @Id
    @GeneratedValue
    private Integer id;
    private Integer pid;
    private int articleId;
    private int userId;
    private String content;
    private byte status;
    private String ip;
    private String agent;
    private Integer systemId;
    private long ctime;

    public Comment() {
    }

    public Comment(int articleId, int userId, String content, byte status, long ctime) {
        this.articleId = articleId;
        this.userId = userId;
        this.content = content;
        this.status = status;
        this.ctime = ctime;
    }

    public Comment(Integer pid, int articleId, int userId, String content, byte status, String ip, String agent,
            Integer systemId, long ctime) {
        this.pid = pid;
        this.articleId = articleId;
        this.userId = userId;
        this.content = content;
        this.status = status;
        this.ip = ip;
        this.agent = agent;
        this.systemId = systemId;
        this.ctime = ctime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPid() {
        return this.pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    public int getArticleId() {
        return this.articleId;
    }

    public void setArticleId(int articleId) {
        this.articleId = articleId;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public byte getStatus() {
        return this.status;
    }

    public void setStatus(byte status) {
        this.status = status;
    }

    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getAgent() {
        return this.agent;
    }

    public void setAgent(String agent) {
        this.agent = agent;
    }

    public Integer getSystemId() {
        return this.systemId;
    }

    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    public long getCtime() {
        return this.ctime;
    }

    public void setCtime(long ctime) {
        this.ctime = ctime;
    }

}
