package com.leecp.jpa.model;
// Generated 2018-2-22 20:11:02 by Hibernate Tools 5.2.8.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Menu generated by hbm2java
 */
@Entity
public class Menu implements java.io.Serializable {
    @Id
    @GeneratedValue
    private Integer id;
    private Integer pid;
    private String name;
    private String url;
    private String target;
    private Long orders;

    public Menu() {
    }

    public Menu(Integer pid, String name, String url, String target, Long orders) {
        this.pid = pid;
        this.name = name;
        this.url = url;
        this.target = target;
        this.orders = orders;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPid() {
        return this.pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getTarget() {
        return this.target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    public Long getOrders() {
        return this.orders;
    }

    public void setOrders(Long orders) {
        this.orders = orders;
    }

}
